# Number of messages per day
n_per_day: 40

# Short sleep
short_sleep: 5

# Short sleep noise
short_sleep_noise: 1

# Long sleep noise in minutes
long_sleep_noise: 3

# is_test
is_test: False

# What percent of tweets should be tweeting an article
gpt_percent: 0.05
